### ISSUE TITLE
Step vs Next

### ISSUE THREAD

**Issue by mbartling** [mbartling/QtLC3#5]
Need someone to implement Step vs Next functionality in the simulator.

https://sourceware.org/gdb/onlinedocs/gdb/Continuing-and-Stepping.html

**Comment by theotherjimmy** [comment]
Given that the LC3 has no dedicated Call/Return instructions, we expect that the users of this simulator will only be used by assembly language programmers, and next and step are both defined with C debug symbols in mind; can we faithfully recreat the step and next behaviors?

**Comment by theotherjimmy** [comment]
offline discussions have lead me to the conclusion that I should implement next anyway.
